SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE vender_entrada(
    p_asistente_id NUMBER,
    p_concierto_id NUMBER,
    p_tipo_entrada VARCHAR2
) IS
    NUM_ENTRADAS NUMBER(5);
    CAPACIDAD_ESCENARIO NUMBER (5);
    PORCENTAJE_OCUPACION NUMBER(3);
    PRECIOTOTAL NUMBER(3);
    ID_ENTRADA NUMBER;
    ID_CONFIRMACION INTEGER;
    CODIGO_QR VARCHAR(100);
BEGIN
    SELECT COUNT(*) INTO NUM_ENTRADAS FROM ENTRADA WHERE CONCIERTO_ID = P_CONCIERTO_ID;
    SELECT CAPACIDAD INTO CAPACIDAD_ESCENARIO FROM ESCENARIO WHERE ID = (SELECT ESCENARIO_ID FROM CONCIERTO WHERE ID = P_CONCIERTO_ID);
    SELECT NVL(MAX(ID), 0) + 1 INTO ID_ENTRADA FROM ENTRADA;
    
    IF NUM_ENTRADAS = 0 THEN
        PORCENTAJE_OCUPACION := 0;
    ELSE
        PORCENTAJE_OCUPACION := (CAPACIDAD_ESCENARIO * 10) / NUM_ENTRADAS;
    END IF;

    IF PORCENTAJE_OCUPACION <= 90 THEN
        IF P_TIPO_ENTRADA = 'VIP' THEN
            PRECIOTOTAL := 100;
        ELSIF P_TIPO_ENTRADA = 'PREMIUM' THEN
            PRECIOTOTAL := 150;
        ELSIF P_TIPO_ENTRADA = 'GENERAL' THEN
            PRECIOTOTAL := 50;
        ELSE
            DBMS_OUTPUT.PUT_LINE ('EL TIPO DE ENTRADA INDICADA ES INCORRECTA');
        END IF;
        codigo_qr := 'QR-' || TO_CHAR(ID_ENTRADA);
        INSERT INTO ENTRADA VALUES (ID_ENTRADA, P_ASISTENTE_ID, P_CONCIERTO_ID, SYSDATE, PRECIOTOTAL, P_TIPO_ENTRADA, codigo_qr, 'VALIDA');
        SELECT ID INTO ID_CONFIRMACION FROM ENTRADA WHERE ID = ID_ENTRADA;
        IF ID_CONFIRMACION = ID_ENTRADA THEN
            DBMS_OUTPUT.PUT_LINE ('LA ENTRADA HA SIDO CREADA CON EXITO');
        ELSE
            DBMS_OUTPUT.PUT_LINE ('LA ENTRADA NO HA SIDO CREADA CON EXITO');
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE ('HAY UNA OCUPACIÓN MAYOR AL 90%, POR LO QUE NO SE PUEDE INSERTAR NINGUNA ENTRADA A DICHO CONCIERTO');
    END IF;
END;
/

EXEC VENDER_ENTRADA(1, 7, 'VIP');
